//
//  BWStyleKit.m
//  BorderWait
//
//  Created by Alice Nguyen on 12/22/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "BWStyleKit.h"


@implementation BWStyleKit

#pragma mark Cache

static UIColor* _green500 = nil;
static UIColor* _amber500 = nil;
static UIColor* _red500 = nil;

static UIImage* _imageOfGreenDot = nil;
static UIImage* _imageOfYellowDot = nil;
static UIImage* _imageOfRedDot = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _green500 = [UIColor colorWithRed: 0.298 green: 0.686 blue: 0.314 alpha: 1];
    _amber500 = [UIColor colorWithRed: 1 green: 0.757 blue: 0.027 alpha: 1];
    _red500 = [UIColor colorWithRed: 0.957 green: 0.263 blue: 0.212 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)green500 { return _green500; }
+ (UIColor*)amber500 { return _amber500; }
+ (UIColor*)red500 { return _red500; }

#pragma mark Drawing Methods

+ (void)drawGreenDot
{

    //// dot Drawing
    UIBezierPath* dotPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(0.5, 1.5, 52, 52)];
    [BWStyleKit.green500 setFill];
    [dotPath fill];
    [BWStyleKit.green500 setStroke];
    dotPath.lineWidth = 1;
    [dotPath stroke];
}

+ (void)drawYellowDot
{

    //// dot Drawing
    UIBezierPath* dotPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(1.5, 1.5, 52, 52)];
    [BWStyleKit.amber500 setFill];
    [dotPath fill];
    [BWStyleKit.amber500 setStroke];
    dotPath.lineWidth = 1;
    [dotPath stroke];
}

+ (void)drawRedDot
{

    //// dot Drawing
    UIBezierPath* dotPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(1.5, 0.5, 52, 52)];
    [BWStyleKit.red500 setFill];
    [dotPath fill];
    [BWStyleKit.red500 setStroke];
    dotPath.lineWidth = 1;
    [dotPath stroke];
}

+ (void)drawCanvas2
{
}

#pragma mark Generated Images

+ (UIImage*)imageOfGreenDot
{
    if (_imageOfGreenDot)
        return _imageOfGreenDot;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(55, 55), NO, 0.0f);
    [BWStyleKit drawGreenDot];

    _imageOfGreenDot = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfGreenDot;
}

+ (UIImage*)imageOfYellowDot
{
    if (_imageOfYellowDot)
        return _imageOfYellowDot;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(55, 55), NO, 0.0f);
    [BWStyleKit drawYellowDot];

    _imageOfYellowDot = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfYellowDot;
}

+ (UIImage*)imageOfRedDot
{
    if (_imageOfRedDot)
        return _imageOfRedDot;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(55, 55), NO, 0.0f);
    [BWStyleKit drawRedDot];

    _imageOfRedDot = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfRedDot;
}

#pragma mark Customization Infrastructure

- (void)setGreenDotTargets: (NSArray*)greenDotTargets
{
    _greenDotTargets = greenDotTargets;

    for (id target in self.greenDotTargets)
        [target setImage: BWStyleKit.imageOfGreenDot];
}

- (void)setYellowDotTargets: (NSArray*)yellowDotTargets
{
    _yellowDotTargets = yellowDotTargets;

    for (id target in self.yellowDotTargets)
        [target setImage: BWStyleKit.imageOfYellowDot];
}

- (void)setRedDotTargets: (NSArray*)redDotTargets
{
    _redDotTargets = redDotTargets;

    for (id target in self.redDotTargets)
        [target setImage: BWStyleKit.imageOfRedDot];
}


@end
