//
//  BWStyleKit.h
//  BorderWait
//
//  Created by Alice Nguyen on 12/27/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface BWStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* greenDotTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* yellowDotTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* redDotTargets;

// Colors
+ (UIColor*)green500;
+ (UIColor*)amber500;
+ (UIColor*)red500;

// Drawing Methods
+ (void)drawGreenDot;
+ (void)drawYellowDot;
+ (void)drawRedDot;
+ (void)drawPortSymbolWithPortInitials: (NSString*)portInitials color:(UIColor*) color;
+ (void)drawCanvas2;

// Generated Images
+ (UIImage*)imageOfGreenDot;
+ (UIImage*)imageOfYellowDot;
+ (UIImage*)imageOfRedDot;
+ (UIImage*)imageOfPortSymbolWithPortInitials: (NSString*)portInitials color:(UIColor*) color;

@end
